#!/usr/bin/env bash
set -euo pipefail

EXT_ROOT=$(realpath ~/.local/share/gnome-shell/extensions)
EXT_PATH="${EXT_ROOT}/solar-13@local"

main()
{
    cmd=${1:-local}
    case ${cmd} in
        deploy)
            printf "(re)deploying extension\n"
            cd src
            zip ../solar-13@local.zip ./*
            cd ..
            gnome-extensions install --force solar-13@local.zip
            gnome-extensions enable solar-13@local
            ;;
        *)
            echo "Don't know $@ ..."
            ;;
    esac
}

main "$@"
